invoke-webrequest
Set-ExecutionPolicy
Set-MasterBootRecord
Get-WMIObject
Get-GPPPassword
Get-Keystrokes
Get-TimedScreenshot
Get-VaultCredential
GetServiceUnquoted
Get-ServiceEXEPerms
Get-ServicePerms
Get-RegAlwaysInstallElevated
Get-RegAutoLogon
Get-UnattendedInstallFiles
Get-Webconfig
Get-ApplicationHost
Get-PassHashes
Get-LsaSecret
GetInformation
Get-PSADForestInfo
Get-KerberosPolicy
Get-PSADForestKRBTGTInfo
Get-PSADForestInfo
GetKerberosPolicy
Invoke-Command
Invoke-Expression
iex
Invoke-Shellcode
Invoke--Shellcode
Invoke-ShellcodeMSIL
InvokeMimikatzWDigestDowngrade
Invoke-NinjaCopy
Invoke-CredentialInjection
Invoke-TokenManipulation
InvokeCallbackIEX
Invoke-PSInject
Invoke-DllEncode
Invoke-ServiceUserAdd
Invoke-ServiceCMD
Invoke-ServiceStart
Invoke-ServiceStop
Invoke-ServiceEnable
Invoke-ServiceDisable
Invoke-FindDLLHijack
Invoke-FindPathHijack
Invoke-AllChecks
Invoke-MassCommand
Invoke-MassMimikatz
Invoke-MassSearch
Invoke-MassTemplate
Invoke-MassTokens
Invoke-ADSBackdoor
Invoke-CredentialsPhish
Invoke-BruteForce
Invoke-PowerShellIcmp
Invoke-PowerShellUdp
Invoke-PsGcatAgent
Invoke-PoshRatHttps
Invoke-PowerShellTcp
Invoke-PoshRatHttp
Invoke-PowerShellWmi
Invoke-PSGcat
Invoke-Encode
Invoke-Decode
Invoke-CreateCertificate
InvokeNetworkRelay
EncodedCommand
New-ElevatedPersistenceOption
wsman
Enter-PSSession
DownloadString
DownloadFile
Out-Word
Out-Excel
Out-Java
Out-Shortcut
Out-CHM
Out-HTA
Out-Minidump
HTTP-Backdoor
FindAVSignature
DllInjection
ReflectivePEInjection
Base64
System.Reflection
System.Management
Restore-ServiceEXE
Add-ScrnSaveBackdoor
Gupt-Backdoor
Execute-OnTime
DNS_TXT_Pwnage
WriteUserAddServiceBinary
Write-CMDServiceBinary
Write-UserAddMSI
Write-ServiceEXE
Write-ServiceEXECMD
Enable-DuplicateToken
Remove-Update
Execute-DNSTXT-Code
Download-Execute-PS
Execute-CommandMSSQL
Download_Execute
Copy-VSS
Check-VM
Create-MultipleSessions
Run-EXEonRemote
Port-Scan
Remove-PoshRat
TexttoEXE
Base64ToString
StringtoBase64
Do-Exfiltration
Parse_Keys
Add-Exfiltration
AddPersistence
Remove-Persistence
Find-PSServiceAccounts
Discover-PSMSSQLServers
DiscoverPSMSExchangeServers
Discover-PSInterestingServices
Discover-PSMSExchangeServers
DiscoverPSInterestingServices
Mimikatz
powercat
powersploit
PowershellEmpire
Payload
GetProcAddress
